### ISSUE TITLE
PHP 7.2 support

### ISSUE THREAD

**Issue by antonsmithnz** [silverstripe/silverstripe-saml#12]
I see that `ext-mcrypt` is no longer a requirement for the new php-saml 3.0 version released a few days ago https://github.com/onelogin/php-saml/issues/255

It would be great if php-saml was upgraded in this module so we can use PHP 7.2.

Are there any plans to do this?

**Comment by madmatt** [comment]
PR #14 has done this already, just needs some minor changes and can be merged. I'd be keen to see a stable version tagged at that point too.

**Comment by NightJar** [comment]
#14 merged and therefore closes this :)

**Comment by madmatt** [comment]
Thanks @antons-, please let us know if you have any issues with the new stable v1.0.0 version of the module!
