### ISSUE TITLE
GUID validation is incorrect

### ISSUE THREAD

**Issue by JakubDolba** [silverstripe/silverstripe-saml#19]
current `\SilverStripe\SAML\Helpers\SAMLHelper::validGuid` allows:

- only uppercase "guid" 
  - should be case insensitive
- allows actually invalid values to be considered as valid
  - standard guid should be hex range [0-9a-f]
  - current implementation check [A-Z0-9] which allows non-guid to pass validation

expected result of validation: only valid guid format is passing

**Comment by robbieaverill** [comment]
Can you please provide some basic examples of what you're finding correct and incorrect? Are you saying that we should only accept `A-F` range rather than `A-Z`?

**Comment by JakubDolba** [comment]
"textual representation of UUID are represented as 32 hexadecimal (base-16) digits"
source: https://en.wikipedia.org/wiki/Universally_unique_identifier

+ sometimes (microsoft) surrounds guid with brackets { }

only [0-9A-F] range should be accepted as for example Z is not valid character of guid

example:
valid:  `11111111-1111-1111-ffff-000000000000`
invalid: `11111111-zzzz-1111-ffff-000000000000`

created pull request #22
