### ISSUE TITLE
Azure AD Configuration version requirement

### ISSUE THREAD

**Issue by itengineer2020** [silverstripe/silverstripe-saml#30]
We plan to move from ADFS to Azure AD for SSO. Would anyone please let me know what version of Silverstripe-SAML is compatible with Azure AD? Do we need version 4 for this to work? We are using version 3 and I assume since Azure AD use the same SAML protocol, what we need to do is just configuring Silversripe-saml with the new Identity provider (Replace ADFS with Azure AD parameters).

**Comment by baukezwaan** [comment]
We also have used it with Azure on older releases (with the silverstripe/saml version), but only on SilverStripe 4. But there is a good chance that by just replacing the parameters, it will just work. 
There is one easy way to find out for sure... try it ;-)

**Comment by madmatt** [comment]
Hi @itengineer2020, unfortunately it may not be quite that simple. One of the key things you'll need to make sure of is that Azure AD and ADFS return **the same unique value** - e.g. the same GUID - for each user. This can be a little difficult to configure, but the documentation in the module can help guide you there (there's a configuration guide specifically for Azure AD).

There are a couple of differences which are also documented in the developer guide for Azure AD (specifically this section: https://github.com/silverstripe/silverstripe-saml/blob/master/docs/en/developer.md#additional-configuration-for-azure-ad) that would be worth reviewing as well.

**Comment by madmatt** [comment]
I'll mark this issue as closed for now, but please feel free to re-open it or comment on it if you have any other questions! I'm happy to help if I can (although as you can tell I'm not terribly active, sorry about that!)
