### ISSUE TITLE
User is logged out after login and redirect

### ISSUE THREAD

**Issue by Zerogiven** [silverstripe/silverstripe-saml#33]
Hi,

I'm working since hours with a problem, maybe you have an idea ;-)

All looks fine, user get authenticated, is redirected to /saml/acs where the user will be created and logged in after. So the login by the IdentityStore is working without any problem, but after the redirect to the page after the login, i am not logged in anymore and the process starts from beginning (so its going endless from "login cause no user > authenticate > redirect to page after login > no user in session, start again"... this problem is getting me crazy cause i have no idea why it does not save the user in the session...

**Comment by baukezwaan** [comment]
I feel your pain. Some things we have come across in this corner / you can :
- check if domain is the same after the redirect (eg www.domain.tld to domain.tld wouldn't work)
- set a breakpoint in logout-function and see if it is being called (and by whom)
- check if `Security::getCurrentUser()` has a value at beginnin of the redirected page

hope this helpes a bit, good luck!
