### ISSUE TITLE
Refactor SAMLSecurityExtension into SAMLLoginHandler

### ISSUE THREAD

**Issue by sminnee** [silverstripe/silverstripe-saml#4]
The SS4 LoginHandler API is more flexible and it should be possible to shift the code of SAMLSecurityExtension into SAMLLoginHandler::login() or SAMLLoginHandler::loginForm(), removing the need for an extension altogether

**Comment by robbieaverill** [comment]
Yeah! We've done a little work on helping this possibility with the LDAP module and in core as well.

**Comment by NightJar** [comment]
Resolved in https://github.com/silverstripe/silverstripe-saml/commit/16210425ec5e5c8a5347b62974bd63dc7af34c6a#diff-3fb4a0b4d236e79fc456c95e45a3d0f0 by @madmatt Aug 9 (I assume un-PR'd since that date precedes this issue).
