### ISSUE TITLE
PHP8 compatibility

### ISSUE THREAD

**Issue by MelissaWu-SS** [silverstripe/silverstripe-saml#40]
There are two packages that this module requires, `zendframework/zend-session` and `zendframework/zend-authentication` are abandoned now, and they don't support php 8. But after investigation, it is found these two packages are not actually used by the SAML module. We can just remove these two packages from the composer.json of the SAML module. 

Another package that the SAML module requires, `onelogin/php-saml` is in `^3.0.0`, it should be upgraded to the latest version `4.1.0`, which supports PHP 8 well. 

Upgrade the phpunit version to `^9.5` for PHP 8 compatibility.

**Comment by satrun77** [comment]
Fixed thanks to @UndefinedOffset version `2.1.1` released
