### ISSUE TITLE
Azure AD Question

### ISSUE THREAD

**Issue by jordanabc35** [silverstripe/silverstripe-saml#44]
With an enterprise application created in Azure AD, I've set `SP."entityId"` and `IdP.entityId` in the config and EntityID and reply url on the Azure enterprise app to the silverstripe instance's dns name. What do I set the `IdP.singleSignOnService` to? This isn't clear in the documentation, or I'm not understanding it properly.

I also assume I export and store the `Certificate (Base64)` from the Enterprise Application's saml config on the server and set `IdP.x509cert` to this?

**Comment by jordanabc35** [comment]
```
---
Name: mysamlsettings-dev
After: '#samlsettings'
---
SilverStripe\SAML\Services\SAMLConfiguration:
  strict: true
  debug: true
  expect_binary_nameid: false
  SP:
    entityId: "https://silverstripe.domain.dev"
    nameIdFormat: 'urn:oasis:names:tc:SAML:1.1:nameid-format:unspecified'
    privateKey: "/etc/ssl/private/privatekey.pem"
    x509cert: "/etc/ssl/certs/certificate.crt"
  IdP:
    entityId: "https://silverstripe.domain.dev/adfs/services/trust"
    x509cert: "<path-to-adfs-cert>.pem"
    singleSignOnService: "https://<idp-domain>/adfs/ls/"
  Security:
    signatureAlgorithm: "http://www.w3.org/2001/04/xmldsig-more#rsa-sha256"

SilverStripe\SAML\Extensions\SAMLMemberExtension:
  claims_field_mappings:
    'http://schemas.xmlsoap.org/ws/2005/05/identity/claims/name': 'Email'

SilverStripe\Core\Injector\Injector:
  SilverStripe\Security\Security:
    properties:
      Authenticators:
        default: %$SilverStripe\SAML\Authenticators\SAMLAuthenticator```

**Comment by jordanabc35** [comment]
Something tells me it might be this? 
![image](https://user-images.githubusercontent.com/13210689/207967617-3eb8717a-db1f-4cd1-9ff4-306626e715f5.png)

**Comment by baukezwaan** [comment]
> What do I set the IdP.singleSignOnService to? 

For Azure this usually is something like these parameters:
- `IdP.singleSignOnService` = `https://login.microsoftonline.com/xxxxx-yyy-zzzzz-xxxxx/saml2` 
- `IdP.entityId` = `https://login.microsoftonline.com/xxxxx-yyy-zzzzz-xxxxx/` 


> I also assume I export and store the Certificate (Base64) from the Enterprise Application's saml config on the server and set IdP.x509cert to this?

That's correct, we usually link to a `file.crt`, that looks like this:
```
-----BEGIN CERTIFICATE-----
MIIC8DC...
-----END CERTIFICATE-----
```

Hope this helps you a step in the right direction

**Comment by jordanabc35** [comment]
Perfect, thank you so much!
