### ISSUE TITLE
Silverstripe 5 support

### ISSUE THREAD

**Issue by Sitetools** [silverstripe/silverstripe-saml#47]
Could you please let me know if or when you'll offer Silverstripe 5 support?
We use your addon on a few of our key projects and would like to continue using it.
Also do you have a timeline for when you'll support PHP 8.2.

CC @axllent

**Comment by MelissaWu-SS** [comment]
Hey @Sitetools, I am currently working on adding support Silverstripe 5 and PHP 8.1 to this module. Hopefully it can be finished in a few weeks.
