### ISSUE TITLE
SAMLHelper::SAMLConfService not injected/instantiated

### ISSUE THREAD

**Issue by micschk** [silverstripe/silverstripe-saml#6]
Calls to saml/Metadata result in an error because 'SAMLHelper->SAMLConfService' is NULL instead of the SAMLConfiguration object it should be (should get instantiated by the injector from $dependencies?).

SAMLHelper::$dependencies seems correct, it just seems the injector never resolves this dependency. I haven't been able to find out why.

```$this->SAMLConfService->asArray()``` errors along the lines of 'calling asArray on null', while ```\SilverStripe\Core\Injector\Injector::inst()->get(SAMLConfiguration::class)->asArray()``` works OK.

**Comment by dhensby** [comment]
because `SAMLHelper::$dependencies` is declared as `public static` instead of `private static`, I think

**Comment by micschk** [comment]
Well, that's a well spent afternoon... :) PR coming up...
